### ISSUE TITLE
语句可优化

### ISSUE THREAD

**Issue by YangFong** [liweiwei1419/liweiwei1419.github.io#1]
有所重复，可以改成

> 因为有一些内容其实是重合的，还有一些内容是 **现阶段** 我根本不需要的。

![image](https://user-images.githubusercontent.com/70502828/148635752-1db618ea-b0d9-4b1b-b7f0-05335b3841a1.png)

**Comment by liweiwei1419** [comment]
已经按照您的要求更改了，感谢您的支持哦！
