### ISSUE TITLE
内容可优化

### ISSUE THREAD

**Issue by YangFong** [liweiwei1419/liweiwei1419.github.io#2]
- 红：标题错误
- 绿：应该是找卖芒果的（不确定，是否存在版本不同）
- 蓝：或许我更喜欢将 较 换成 比（个人的偏向）
- 黄：最好补充不建议学习的是什么，此处显得与第一句有所冲突

![image](https://user-images.githubusercontent.com/70502828/148636079-6c2d146b-465b-4013-9188-87bc5c63a57c.png)

**Comment by liweiwei1419** [comment]
书名的确是《算法图解》，并且 BFS 的例子是「寻找芒果销售商」，因为生活中不太会「寻找芒果销售商」，找教师、医生、律师的事情还蛮多的，所以我就记成找律师了，感谢指出问题哟！
