### ISSUE TITLE
内容建议

### ISSUE THREAD

**Issue by YangFong** [liweiwei1419/liweiwei1419.github.io#3]
- 下载格式可以考虑统一
- 篮圈似乎缺少了分隔符

![image](https://user-images.githubusercontent.com/70502828/148722435-26156b86-a5cf-4479-a54a-3cb5d2c5b53e.png)

---

题外话，我在另一个仓库中，发现链接跳转存在问题，如有空闲请处理一下。

**Comment by liweiwei1419** [comment]
谢谢你看得这么认真，我今天会改一下格式。

这个网站还有很多地方格式很不好，如果你看到觉得影响自己和他人阅读，可以甩一个链接到 issue 来，我看到了都会处理的。
