### ISSUE TITLE
左侧导航格式

### ISSUE THREAD

**Issue by YangFong** [liweiwei1419/liweiwei1419.github.io#4]
发现左侧导航标题格式未统一。

![image](https://user-images.githubusercontent.com/70502828/148886634-a82db1b8-e841-4722-bf9f-b28463dd3072.png)

---

另外，在阅读配置文件时，观察到有部分格式未统一（单双引号、结尾逗号与文件缩进），我推荐添加 **Prettier** 进行辅助开发。

![image](https://user-images.githubusercontent.com/70502828/148887083-586c1c80-dae1-44ad-ac1a-8e9c1cc08edf.png)

**Comment by liweiwei1419** [comment]
感谢纠正，已经统一用「章」来表示大标题。

您推荐的 vscode 的 Prettier 插件很好用，我已经用在项目中啦，谢谢！
